### PR TITLE
apache-arrow 3.0.0

### PR DESCRIPTION
**Pull request by nealrichardson**
See also https://github.com/r-windows/rtools-packages/pull/184

### CODE REVIEW

**Comment by jeroen** [comment]
High-sierra looks OK but the build on el-capitain (osx 10.11) failed with:
```
/tmp/apache-arrow-20210116-6233-1jyrhk8/apache-arrow-3.0.0/cpp/src/arrow/dataset/expression.cc
/tmp/apache-arrow-20210116-6233-1jyrhk8/apache-arrow-3.0.0/cpp/src/arrow/dataset/expression.cc:684:30: error: default initialization of an object of const type 'const arrow::Datum' without a user-provided default constructor
          static const Datum ignored_input;
                             ^
                                          {}
```
and
```
In file included from /tmp/apache-arrow-20210116-6233-1jyrhk8/apache-arrow-3.0.0/cpp/src/arrow/io/caching.cc:26:
/tmp/apache-arrow-20210116-6233-1jyrhk8/apache-arrow-3.0.0/cpp/src/arrow/util/future.h:102:3: error: default initialization of an object of const type 'const struct ContinueFuture' without a user-provided default constructor
} Continue;
  ^
          {}
1 error generated.
```

So if we want to keep supporting R 3.6 we need to find a workaround for that.

**Comment by nealrichardson** [comment]
Ok, we can work out a patch for that.
https://issues.apache.org/jira/browse/ARROW-11277

**Comment by jeroen** [comment]
@bkietz do you have any suggestion how I can work around this?

**Comment by bkietz** [comment]
@jeroen https://github.com/apache/arrow/pull/9267

**Comment by jeroen** [comment]
Thanks let me test that

**Comment by jeroen** [comment]
Seems to work, awesome.
